{
  config,
  pkgs,
  host,
  inputs,
  username,
  options,
  ...
}: 
{
    imports = [
        ./boot.nix
        ./bluetooth.nix
        ./cache.nix
        ./displaymanager.nix
        ./locale.nix
        ./gaming.nix
        ./graphics.nix
        ./nix_settings.nix
        ./pkgs_stable.nix
        ./pkgs_unstable.nix
        #./power.nix
        ./proton.nix
        ./sound.nix
        ./upgrade.nix
    ];
}