"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """$status """

right_format = "$git_branch $git_metrics$directory"

[status]
symbol          = " [ ](bg:#1e191e fg:#0c4f63)[∆](fg:#b36c4b bg:#1e191e)[ ](bg:#1e191e fg:#0c4f63)"
success_symbol  = " [ ](bg:#1e191e fg:#91a3b0)[∆](fg:#4a5a64 bg:#1e191e)[ ](bg:#1e191e fg:#91a3b0)"
disabled = false
format = '$symbol'

[directory]
disabled = false
format = " [ ](fg:#2e191e bg:#848C94)[   ┃ $path ](bg:#848C94 fg:#1e191e)[ ](fg:#1e191e bg:#848C94) "

[git_branch]
symbol = ''
format = '[$symbol $branch](fg:#b1a7a8 bg:#1e191e) '

[git_metrics]
disabled = false
only_nonzero_diffs = false
format = '[ ](fg:#1e191e bg:#8c7d7b)[ +$added ](fg:#1e191e bg:#8c7d7b)[┃](bg:#8c7d7b fg:#1e191e)[ -$deleted ](fg:#1e191e bg:#8c7d7b)[ ](fg:#1e191e bg:#8c7d7b)'