{
  config,
  pkgs,
  host,
  inputs,
  username,
  options,
  ...
}: 
{
    imports = [
        #./firefox.nix
        ./direnv.nix
        #./bat.nix
        ./cava.nix
        #./idleinhibitor.nix
        ./gnome.nix
        ./gnome-extensions.nix
        ./git.nix
        ./zsh.nix
        ./chromium.nix
        ./hypridle.nix
        ./spicetify.nix
    ];
}